import type { BuyingGuideData } from '@/lib/buyingGuides'

const data: Omit<BuyingGuideData, 'slug' | 'overviewMdx'> = {
  name: "Watch Buying Guide: Under $500",
  shortLabel: "Under $500",
  dbValue: "Under $500",
  lastUpdated: "April 2026",
  intro: "10 picks under $500 — mechanical automatics, solar divers, and Swiss quartz — each chosen for a specific use case. Prices verified against current retail.",
  heroFact: "The Seiko 5 Sports GMT — a mechanical GMT with a dedicated 24-hour hand — retails for $495. The same complication from Swiss brands typically starts at $800–$1,500.",
  whoItIsFor: [
    {
      profile: "First-time buyer",
      description: "You want a well-made watch without overspending before you know what you like. The Seiko 5 Sports SRPD55 is the default answer.",
    },
    {
      profile: "Daily beater",
      description: "You need 100m+ water resistance, a tough crystal, and a movement that doesn't need babying. The Citizen Promaster Diver handles this without compromise.",
    },
    {
      profile: "Style-forward buyer",
      description: "You want something that looks more expensive than it is. The Citizen Tsuyosa (sapphire, integrated bracelet) and Tissot PRX (Swiss Made, 1970s profile) are the picks.",
    },
    {
      profile: "Upgrading from fashion brands",
      description: "You've worn MVMT or Daniel Wellington and want a real mechanical movement and a name that holds up to scrutiny. Orient Bambino or Seiko 5 Sports.",
    },
    {
      profile: "Gift buyer",
      description: "You need a legitimate name without overcommitting. Seiko and Hamilton are safe choices — recognisable, well-reviewed, available at retail.",
    },
  ],
  pickByUseCase: [
    { useCase: "First automatic", model: "Seiko 5 Sports SRPD55" },
    { useCase: "Dive watch", model: "Citizen Promaster Diver BN0150-28E" },
    { useCase: "GMT / travel", model: "Seiko 5 Sports GMT SSK001" },
    { useCase: "Dress watch", model: "Orient Bambino RA-AC0001S" },
    { useCase: "Integrated bracelet", model: "Citizen Tsuyosa NJ0150-81L" },
    { useCase: "Indestructible", model: "Casio G-Shock DW-5600E-1V" },
    { useCase: "Swiss Made", model: "Tissot PRX T137.210.11.031.00" },
  ],
  notableModels: [
    {
      name: "Seiko 5 Sports SRPD55",
      brandName: "Seiko",
      price: "~$350",
      caseSize: "42.5mm",
      waterResistance: "100m",
      crystal: "Hardlex",
      movement: "Automatic (4R36)",
      bestFor: "Best first automatic",
      reason: "The 4R36 calibre gives you day/date display, hand-winding, and hacking at ~$350 — more functionality than most automatics twice the price. 100m water resistance makes it genuinely wearable anywhere.",
      tradeoff: "Hardlex crystal scratches more easily than sapphire; bracelet clasp feels loose compared to the $500+ tier.",
      communitySignal: "The default r/Watches recommendation for first-time buyers for over a decade.",
      imageUrl: "https://images.unsplash.com/photo-1612817288484-6f916006741a?w=400&q=80&fit=crop",
    },
    {
      name: "Seiko 5 Sports GMT SSK001",
      brandName: "Seiko",
      price: "~$495",
      caseSize: "42.5mm",
      waterResistance: "100m",
      crystal: "Hardlex with lenses",
      movement: "Automatic GMT (4R34)",
      bestFor: "Best mechanical GMT",
      reason: "A genuine mechanical GMT — 24-hour hand, bidirectional bezel — for $495. Swiss brands charge $800+ for the same complication. The SSK001 in black/green is the best-selling variant.",
      tradeoff: "The 4R34 movement runs to ±15 seconds/day; less accurate than a quartz but part of the mechanical charm.",
      communitySignal: "Praised on WatchUSeek as the most accessible mechanical GMT — the value-to-complication ratio is hard to argue with.",
      imageUrl: "https://images.unsplash.com/photo-1533139502658-0198f920d8e8?w=400&q=80&fit=crop",
    },
    {
      name: "Orient Bambino RA-AC0001S",
      brandName: "Orient",
      price: "~$250",
      caseSize: "40.5mm",
      waterResistance: "30m",
      crystal: "Domed Mineral",
      movement: "Automatic (Orient F6724)",
      bestFor: "Best dress automatic",
      reason: "An in-house movement with hand-winding and hacking at ~$250 — features typically found at $500+. The domed dial and crystal give it a vintage look that reads as significantly more expensive.",
      tradeoff: "30m water resistance means splash-proof only — not suitable for swimming.",
      communitySignal: "Consistently cited as the dress watch to buy before you can justify spending more.",
      imageUrl: "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=400&q=80&fit=crop",
    },
    {
      name: "Citizen Tsuyosa NJ0150-81L",
      brandName: "Citizen",
      price: "~$350",
      caseSize: "40mm",
      waterResistance: "50m",
      crystal: "Sapphire",
      movement: "Automatic (Caliber 8210)",
      bestFor: "Best integrated bracelet",
      reason: "Sapphire crystal and a true integrated bracelet at ~$350 — a combination you'd normally pay $800+ for. The NJ0150-81L in blue is the standout colourway.",
      tradeoff: "50m water resistance is the one limitation; not suitable for serious water activities.",
      communitySignal: "Frequently described as an Omega Aqua Terra alternative at a fraction of the cost.",
      imageUrl: "https://images.unsplash.com/photo-1619134778706-7015533a6150?w=400&q=80&fit=crop",
    },
    {
      name: "Citizen Promaster Diver BN0150-28E",
      brandName: "Citizen",
      price: "~$295",
      caseSize: "44mm",
      waterResistance: "200m",
      crystal: "Anti-reflective mineral",
      movement: "Eco-Drive solar (E168)",
      bestFor: "Best tool diver",
      reason: "ISO 6425 certified — the same standard applied to professional dive watches — with 200m water resistance and a solar movement that never needs a battery. The most capable tool watch in this guide.",
      tradeoff: "44mm case is large on smaller wrists; the solar movement removes the ritual of mechanical winding.",
      communitySignal: "The value benchmark in dive watch communities — cited by Worn & Wound and WatchUSeek for its ISO certification.",
      imageUrl: "https://images.unsplash.com/photo-1548171916-c8fd5d49f80a?w=400&q=80&fit=crop",
    },
    {
      name: "Casio G-Shock DW-5600E-1V",
      brandName: "Casio",
      price: "~$70",
      caseSize: "42.8mm",
      waterResistance: "200m",
      crystal: "Mineral",
      movement: "Quartz (Module 3229)",
      bestFor: "Best for pure durability",
      reason: "Shock-resistant, 200m water resistant, and runs for years on a single battery — for $70. Nothing else at any price tier matches it for resilience. The DW-5600E-1V is the original square G-Shock.",
      tradeoff: "Polarising aesthetic — the square case and digital display won't work for dress or office contexts.",
      communitySignal: "Near-universal praise from military, outdoor, and everyday-carry communities.",
      imageUrl: "https://images.unsplash.com/photo-1625513867786-f8b2c2cc2be5?w=400&q=80&fit=crop",
    },
    {
      name: "Tissot PRX T137.210.11.031.00",
      brandName: "Tissot",
      price: "~$450",
      caseSize: "35mm",
      waterResistance: "100m",
      crystal: "Sapphire",
      movement: "Quartz (ETA F05.115)",
      bestFor: "Best Swiss Made quartz",
      reason: "Swiss Made, sapphire crystal, and a 1970s integrated bracelet profile at ~$450. The ETA F05.115 quartz movement delivers ±0.07 seconds/day accuracy. Thinnest watch in this guide at 9.9mm.",
      tradeoff: "35mm diameter reads small on larger wrists; the quartz movement won't satisfy buyers who want mechanical.",
      communitySignal: "Gained significant attention via Hodinkee for its resemblance to vintage Patek Nautilus proportions.",
      imageUrl: "https://images.unsplash.com/photo-1594534475808-b18fc33b045e?w=400&q=80&fit=crop",
    },
    {
      name: "Hamilton Khaki Field H69439931",
      brandName: "Hamilton",
      price: "~$495",
      caseSize: "38mm",
      waterResistance: "50m",
      crystal: "Sapphire",
      movement: "Manual-wind (ETA 2801-2)",
      bestFor: "Best field watch",
      reason: "Swiss Made, sapphire crystal, 80-hour power reserve, hand-wound — all for $495. The 38mm case and slim profile wear well under a cuff. High-contrast dial with luminous hands prioritises legibility.",
      tradeoff: "Manual winding requires daily attention; 50m water resistance limits water activities.",
      communitySignal: "Cited on Worn & Wound as the definitive affordable field watch — manual winding is a feature, not a drawback.",
      imageUrl: "https://images.unsplash.com/photo-1547996160-81dfa63595aa?w=400&q=80&fit=crop",
    },
    {
      name: "Seiko Prospex Alpinist SPB117J1",
      brandName: "Seiko",
      price: "~$450",
      caseSize: "38mm",
      waterResistance: "200m",
      crystal: "Sapphire",
      movement: "Automatic (Caliber 6R35)",
      bestFor: "Best outdoor automatic",
      reason: "Sapphire crystal, 200m water resistance, internal compass bezel, and 70-hour power reserve in a 38mm case. The green pyramid-textured dial is frequently mistaken for a much more expensive watch.",
      tradeoff: "The internal rotating bezel is unusual — takes adjustment if you're used to external bezels.",
      communitySignal: "Strong following among Seiko enthusiasts and outdoor communities for the 6R35 movement at this price point.",
      imageUrl: "https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=400&q=80&fit=crop",
    },
    {
      name: "Timex Marlin TW2T22700",
      brandName: "Timex",
      price: "~$200",
      caseSize: "40mm",
      waterResistance: "30m",
      crystal: "Acrylic (domed)",
      movement: "Automatic (Miyota 8215)",
      bestFor: "Best vintage aesthetic",
      reason: "A reissue of Timex's 1960s dress watch — domed acrylic crystal, cream sunburst dial, genuine automatic movement for ~$200. The Miyota 8215 is reliable and widely serviced.",
      tradeoff: "Acrylic crystal scratches easily (though it can be polished); 30m water resistance means splash-proof only.",
      communitySignal: "The go-to recommendation for buyers who prioritise aesthetics and vintage character over tool specs.",
      imageUrl: "https://images.unsplash.com/photo-1622434641406-a158123450f2?w=400&q=80&fit=crop",
    },
  ],
  faq: [
    {
      question: "What is the best automatic watch under $500?",
      answer: "The Seiko 5 Sports SRPD55 (~$350) is the most versatile — day/date, 100m water resistance, proven 4R36 calibre. If you want a complication, the Seiko 5 Sports GMT SSK001 (~$495) adds a mechanical GMT function that Swiss brands charge $800+ for. For dress, the Orient Bambino (~$250) is the strongest pick.",
    },
    {
      question: "Is sapphire crystal available under $500?",
      answer: "Yes — on specific models. The Citizen Tsuyosa (~$350), Tissot PRX (~$450), Hamilton Khaki Field (~$495), and Seiko Prospex Alpinist (~$450) all include sapphire. The Seiko 5 Sports uses Hardlex, which is harder than standard mineral but not as scratch-resistant as sapphire.",
    },
    {
      question: "Seiko 5 Sports vs Citizen Tsuyosa — which should I buy?",
      answer: "The Seiko 5 Sports wins on water resistance (100m vs 50m) and proven track record. The Tsuyosa wins on aesthetics — sapphire crystal and integrated bracelet at the same price. Choose Seiko if you'll wear it hard; choose Tsuyosa if you want it to look more expensive.",
    },
    {
      question: "What do I give up compared to the $500–$1,000 tier?",
      answer: "Better bracelet finishing, sapphire crystal on almost every model, COSC-certified movements (±4 sec/day), and cleaner case polishing. The movements in this tier are just as durable — the differences are aesthetic, not mechanical.",
    },
    {
      question: "Can I find a genuine ISO-certified dive watch under $500?",
      answer: "Yes. The Citizen Promaster Diver BN0150-28E (~$295) is ISO 6425 certified with 200m water resistance and a solar movement that never needs a battery. It's the most capable tool watch in this guide.",
    },
    {
      question: "Seiko 5 Sports vs Seiko 5 Sports GMT — what's the difference?",
      answer: "The standard 5 Sports uses the 4R36 (day/date automatic). The GMT adds the 4R34 calibre — a 24-hour hand and bidirectional bezel for tracking a second time zone. The GMT costs ~$145 more. If you travel, the GMT is exceptional value. If you don't, the standard is the better daily watch.",
    },
  ],
  internalLinks: [
    { label: "Seiko", href: "/brand/seiko" },
    { label: "Citizen", href: "/brand/citizen" },
    { label: "Orient", href: "/brand/orient" },
    { label: "Tissot", href: "/brand/tissot" },
    { label: "Hamilton", href: "/brand/hamilton" },
    { label: "Casio", href: "/brand/casio" },
    { label: "Timex", href: "/brand/timex" },
    { label: "Dive Watches", href: "/style/dive-watches" },
    { label: "Dress Watches", href: "/style/dress-watches" },
    { label: "GMT Watches", href: "/style/gmt-watches" },
    { label: "Field Watches", href: "/style/field-watches" },
    { label: "Tool Watches", href: "/style/tool-watches" },
    { label: "Casual Watches", href: "/style/casual-watches" },
  ],
  sources: [
    { label: "Seiko 5 Sports SRPD55 — official specs", url: "https://www.seikowatches.com/global-en/products/5sports/srpd55k1" },
    { label: "Seiko 5 Sports GMT SSK001 — official specs", url: "https://www.seikowatches.com/global-en/products/5sports/ssk001k1" },
    { label: "Seiko Prospex Alpinist SPB117J1 — official specs", url: "https://www.seikowatches.com/global-en/products/prospex/spb117j1" },
    { label: "Orient Bambino RA-AC0001S — official specs", url: "https://www.orient-watch.com/collections/bambino" },
    { label: "Citizen Tsuyosa NJ0150-81L — official specs", url: "https://www.citizenwatch.com/us/en/collection/tsuyosa/" },
    { label: "Citizen Promaster Diver BN0150-28E — official specs", url: "https://www.citizenwatch.com/us/en/collection/promaster/" },
    { label: "Tissot PRX T137.210.11.031.00 — official specs", url: "https://www.tissotwatches.com/en-en/tissot-prx.html" },
    { label: "Hamilton Khaki Field H69439931 — official specs", url: "https://www.hamiltonwatch.com/en-gb/collection/khaki-field/khaki-field-mechanical.html" },
    { label: "Casio G-Shock DW-5600E-1V — official specs", url: "https://www.casio.com/us/watches/gshock/product.DW-5600E-1V/" },
    { label: "Timex Marlin TW2T22700 — official specs", url: "https://www.timex.com/marlin-automatic" },
    { label: "r/Watches — Best watches under $500 megathread", url: "https://www.reddit.com/r/Watches/wiki/index" },
    { label: "Hodinkee — Tissot PRX review", url: "https://www.hodinkee.com/articles/tissot-prx-review" },
    { label: "Worn & Wound — Hamilton Khaki Field review", url: "https://wornandwound.com/review-hamilton-khaki-field-mechanical/" },
    { label: "Worn & Wound — Citizen Promaster dive watch review", url: "https://wornandwound.com/review-citizen-promaster-diver/" },
    { label: "WatchUSeek — Seiko 5 Sports GMT forum discussion", url: "https://www.watchuseek.com/threads/seiko-5-sports-gmt.5369735/" },
    { label: "ISO 6425:2018 — Diving watches standard", url: "https://www.iso.org/standard/68531.html" },
  ],
  images: {
    hero: "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=1200&q=80&fit=crop",
    mid:  "https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?w=1200&q=80&fit=crop",
  },
}

export default data
